const urlGermany = "https://api.corona-zahlen.org/germany";
const urlVaccinations = "https://api.corona-zahlen.org/vaccinations";
const urlTesting = "https://api.corona-zahlen.org/testing/history";
const urlState = "https://api.corona-zahlen.org/states";
const urlDistrict = "https://api.corona-zahlen.org/districts";
const urlAge = "https://api.corona-zahlen.org/germany/age-groups";

async function getData(url) {

    const response = await fetch(url);

    var data = await response.json();

    if(response) {
        //hide loading
    }

    if(url === urlGermany) {
        showGermany(data);
        showMeta(data);
    }
    
    if(url === urlVaccinations) {
        showVaccinations(data);
    }

    if(url === urlTesting) {
        showTesting(data);
    }

    if(url === urlState) {
        showState(data);
    }

    if(url === urlDistrict) {
        showDistrict(data);
    }

    if(url === urlAge) {
        showFemale(data);
        showMale(data);
    }
}

getData(urlGermany);
getData(urlVaccinations);
getData(urlTesting);
getData(urlState);
getData(urlDistrict);
getData(urlAge);

fillSelectStates();
test();

function showGermany(data) {
    document.getElementById("cases").innerHTML += formatNumber(data.cases);
    document.getElementById("casesToday").innerHTML += formatNumber(data.delta.cases);
    document.getElementById("recovered").innerHTML += formatNumber(data.recovered);
    document.getElementById("recoveredToday").innerHTML += formatNumber(data.delta.recovered);
    document.getElementById("deaths").innerHTML += formatNumber(data.deaths);
    document.getElementById("deathsToday").innerHTML += formatNumber(data.delta.deaths);
    document.getElementById("weekIncidence").innerHTML += roundNumber(data.weekIncidence);
    document.getElementById("casesPer100k").innerHTML += roundNumber(data.casesPer100k);
    document.getElementById("rValue").innerHTML += roundNumber(data.r.value);
    document.getElementById("hospitalizationCases7Days").innerHTML += formatNumber(data.hospitalization.cases7Days);
}

function showVaccinations(data) {
    const path = data.data;

    document.getElementById("vaccinationOne").innerHTML += formatNumber(path.vaccinated);
    document.getElementById("vaccinationOneToday").innerHTML += formatNumber(path.delta);
    document.getElementById("vaccinationOneQuoteTotal").innerHTML += formatPercentage(path.quote);
    document.getElementById("vaccinationOneQuoteUnder").innerHTML += formatPercentage(path.quotes["A05-A17"].total);
    document.getElementById("vaccinationOneQuoteOver").innerHTML += formatPercentage(path.quotes["A18+"].total);

    document.getElementById("vaccinationTwo").innerHTML += formatNumber(path.secondVaccination.vaccinated); 
    document.getElementById("vaccinationTwoToday").innerHTML += formatNumber(path.secondVaccination.delta);
    document.getElementById("vaccinationTwoQuoteTotal").innerHTML += formatPercentage(path.secondVaccination.quote);
    document.getElementById("vaccinationTwoQuoteUnder").innerHTML += formatPercentage(path.secondVaccination.quotes["A05-A17"].total);
    document.getElementById("vaccinationTwoQuoteOver").innerHTML += formatPercentage(path.secondVaccination.quotes["A18+"].total);

    document.getElementById("vaccinationThree").innerHTML += formatNumber(path.boosterVaccination.vaccinated);
    document.getElementById("vaccinationThreeToday").innerHTML += formatNumber(path.boosterVaccination.delta);
    document.getElementById("vaccinationThreeQuoteTotal").innerHTML += formatPercentage(path.boosterVaccination.quote);
    document.getElementById("vaccinationThreeQuoteUnder").innerHTML += formatPercentage(path.boosterVaccination.quotes["A05-A17"].total);
    document.getElementById("vaccinationThreeQuoteOver").innerHTML += formatPercentage(path.boosterVaccination.quotes["A18+"].total);
}

function showTesting(data) {
    const path = data.data.history[data.data.history.length-1];

    document.getElementById("testingCalendarWeek").innerHTML += path.calendarWeek;
    document.getElementById("testingperformedTests").innerHTML += formatNumber(path.performedTests);
    document.getElementById("testingPositiveTests").innerHTML += formatNumber(path.positiveTests);
    document.getElementById("testingPositivityRate").innerHTML += formatPercentage(path.positivityRate);
    document.getElementById("testingLaboratoryCount").innerHTML += formatNumber(path.laboratoryCount);
}

function showMeta(data) {

    var update = JSON.stringify(data.meta.lastUpdate);

    update = update.replaceAll("-",".");

    document.getElementById("metaSource").innerHTML += data.meta.source;
    document.getElementById("metaUpdate").innerHTML += update.substring(1,11);
    document.getElementById("metaInfo").innerHTML += data.meta.info;
}

function showState(data) {
    const path = data.data.NW;

    document.getElementById("stateName").innerHTML += path.name;
    document.getElementById("statePopulation").innerHTML += formatNumber(path.population);
    document.getElementById("stateCases").innerHTML += formatNumber(path.cases);
    document.getElementById("stateCasesToday").innerHTML += formatNumber(path.delta.cases);
    document.getElementById("stateRecovered").innerHTML += formatNumber(path.recovered);
    document.getElementById("stateRecoveredToday").innerHTML += formatNumber(path.delta.recovered);
    document.getElementById("stateDeaths").innerHTML += formatNumber(path.deaths);
    document.getElementById("stateDeathsToday").innerHTML += formatNumber(path.delta.deaths);
    document.getElementById("stateWeekIncidence").innerHTML += roundNumber(path.weekIncidence);
    document.getElementById("stateCasesPer100k").innerHTML += roundNumber(path.casesPer100k);
    document.getElementById("stateHospitalizationCases7Days").innerHTML += formatNumber(path.hospitalization.cases7Days);
}

function showDistrict(data) {
    const path = data.data["05566"];

    document.getElementById("districtName").innerHTML += path.name;
    document.getElementById("districtPopulation").innerHTML += formatNumber(path.population);
    document.getElementById("districtCases").innerHTML += formatNumber(path.cases);
    document.getElementById("districtCasesToday").innerHTML += formatNumber(path.delta.cases);
    document.getElementById("districtRecovered").innerHTML += formatNumber(path.recovered);
    document.getElementById("districtRecoveredToday").innerHTML += formatNumber(path.delta.recovered);
    document.getElementById("districtDeaths").innerHTML += formatNumber(path.deaths);
    document.getElementById("districtDeathsToday").innerHTML += formatNumber(path.delta.deaths);
    document.getElementById("districtWeekIncidence").innerHTML += roundNumber(path.weekIncidence);
    document.getElementById("districtCasesPer100k").innerHTML += roundNumber(path.casesPer100k);
}

function showFemale(data) {
    const path = data.data;

    document.getElementById("FemaleOneCases").innerHTML += formatNumber(path["A00-A04"].casesFemale);
    document.getElementById("FemaleTwoCases").innerHTML += formatNumber(path["A05-A14"].casesFemale);
    document.getElementById("FemaleThreeCases").innerHTML += formatNumber(path["A15-A34"].casesFemale);
    document.getElementById("FemaleFourCases").innerHTML += formatNumber(path["A35-A59"].casesFemale);
    document.getElementById("FemaleFiveCases").innerHTML += formatNumber(path["A60-A79"].casesFemale);
    document.getElementById("FemaleSixCases").innerHTML += formatNumber(path["A80+"].casesFemale);
}

function showMale(data) {
    const path = data.data;

    document.getElementById("MaleOneCases").innerHTML += formatNumber(path["A00-A04"].casesMale);
    document.getElementById("MaleTwoCases").innerHTML += formatNumber(path["A05-A14"].casesMale);
    document.getElementById("MaleThreeCases").innerHTML += formatNumber(path["A15-A34"].casesMale);
    document.getElementById("MaleFourCases").innerHTML += formatNumber(path["A35-A59"].casesMale);
    document.getElementById("MaleFiveCases").innerHTML += formatNumber(path["A60-A79"].casesMale);
    document.getElementById("MaleSixCases").innerHTML += formatNumber(path["A80+"].casesMale);
}

function formatPercentage(number) {
    var percentage;

    percentage = roundNumber(number * 100) + " %";

    return percentage;
}

function roundNumber(number) {
    var rounded;

    rounded = formatNumber(Math.round(number * 100) / 100);

    return rounded;
}

function formatNumber(number) {
    var format;
    
    format = Number(number).toLocaleString("de-DE");

    return format;
}



function fillSelectStates() {
    var selection = document.getElementById("selectState");

    var globalStates = [  
        ["Baden-Württemberg"],
        ["Bayern"],
        ["Berlin"],
        ["Brandenburg"],
        ["Bremen"],
        ["Hamburg"],
        ["Hessen"],
        ["Mecklenburg-Vorpommern"],
        ["Niedersachsen"],
        ["Nordrhein-Westfalen"],
        ["Rheinland-Pfalz"],
        ["Saarland"],
        ["Sachsen"],
        ["Sachsen-Anhalt"],
        ["Schleswig-Holstein"],
        ["Thüringen"]
    ];

    for (let x = 0; x < globalStates.length; x++) {
        
        var option = document.createElement("option");

        option.text = globalStates[x];

        option.value = globalStates[x];

        selection.add(option);
    }
}

function test() {
/*
    districtOne = [
        
            ["Regionalverband Saarbrücken"],
            ["Merzig-Wadern"],
            ["Neunkirchen"],
            ["Saarlouis"],
            ["Saarpfalz-Kreis"],
            ["St. Wendel"],
            ["Berlin Mitte"],
            ["Berlin Friedrichshain-Kreuzberg"],
            ["Berlin Pankow"],
            ["Berlin Charlottenburg-Wilmersdorf"],
            ["Berlin Spandau"],
            ["Berlin Steglitz-Zehlendorf"],
            ["Berlin Tempelhof-Schöneberg"],
            ["Berlin Neukölln"],
            ["Berlin Treptow-Köpenick"],
            ["Berlin Marzahn-Hellersdorf"],
            ["Berlin Lichtenberg"],
            ["Berlin Reinickendorf"],
            ["Brandenburg an der Havel"],
            ["Cottbus"],
            ["Frankfurt (Oder)"],
            ["Potsdam"],
            ["Barnim"],
            ["Dahme-Spreewald"],
            ["Elbe-Elster"],
            ["Havelland"],
            ["Märkisch-Oderland"],
            ["Oberhavel"],
            ["Oberspreewald-Lausitz"],
            ["Oder-Spree"],
            ["Ostprignitz-Ruppin"],
            ["Potsdam-Mittelmark"],
            ["Prignitz"],
            ["Spree-Neiße"],
            ["Teltow-Fläming"],
            ["Uckermark"],
            ["Rostock"],
            ["Schwerin"],
            ["Mecklenburgische Seenplatte"],
            ["Rostock"],
            ["Vorpommern-Rügen"],
            ["Nordwestmecklenburg"],
            ["Vorpommern-Greifswald"],
            ["Ludwigslust-Parchim"],
            ["Chemnitz"],
            ["Erzgebirgskreis"],
            ["Mittelsachsen"],
            ["Vogtlandkreis"],
            ["Zwickau"],
            ["Dresden"],
            ["Bautzen"],
            ["Görlitz"],
            ["Meißen"],
            ["Sächsische Schweiz-Osterzgebirge"],
            ["Leipzig"],
            ["Leipzig"],
            ["Nordsachsen"],
            ["Dessau-Roßlau"],
            ["Halle (Saale)"],
            ["Magdeburg"],
            ["Altmarkkreis Salzwedel"],
            ["Anhalt-Bitterfeld"],
            ["Börde"],
            ["Burgenlandkreis"],
            ["Harz"],
            ["Jerichower Land"],
            ["Mansfeld-Südharz"],
            ["Saalekreis"],
            ["Salzlandkreis"],
            ["Stendal"],
            ["Wittenberg"],
            ["Erfurt"],
            ["Gera"],
            ["Jena"],
            ["Suhl"],
            ["Weimar"],
            ["Eichsfeld"],
            ["Nordhausen"],
            ["Wartburgkreis"],
            ["Unstrut-Hainich-Kreis"],
            ["Kyffhäuserkreis"],
            ["Schmalkalden-Meiningen"],
            ["Gotha"],
            ["Sömmerda"],
            ["Hildburghausen"],
            ["Ilm-Kreis"],
            ["Weimarer Land"],
            ["Sonneberg"],
            ["Saalfeld-Rudolstadt"],
            ["Saale-Holzland-Kreis"],
            ["Saale-Orla-Kreis"],
            ["Greiz"],
            ["Altenburger Land"],
            ["Flensburg"],
            ["Kiel"],
            ["Lübeck"],
            ["Neumünster"],
            ["Dithmarschen"],
            ["Herzogtum Lauenburg"],
            ["Nordfriesland"],
            ["Ostholstein"],
            ["Pinneberg"],
            ["Plön"],
            ["Rendsburg-Eckernförde"],
            ["Schleswig-Flensburg"],
            ["Segeberg"],
            ["Steinburg"],
            ["Stormarn"],
            ["Hamburg"],
            ["Braunschweig"],
            ["Salzgitter"],
            ["Wolfsburg"],
            ["Gifhorn"],
            ["Goslar"],
            ["Helmstedt"],
            ["Northeim"],
            ["Peine"],
            ["Wolfenbüttel"],
            ["Göttingen"],
            ["Region Hannover"],
            ["Diepholz"],
            ["Hameln-Pyrmont"],
            ["Hildesheim"],
            ["Holzminden"],
            ["Nienburg (Weser)"],
            ["Schaumburg"],
            ["Celle"],
            ["Cuxhaven"],
            ["Harburg"],
            ["Lüchow-Dannenberg"],
            ["Lüneburg"],
            ["Osterholz"],
            ["Rotenburg (Wümme)"],
            ["Heidekreis"],
            ["Stade"],
            ["Uelzen"],
            ["Verden"],
            ["Delmenhorst"],
            ["Emden"],
            ["Oldenburg (Oldb)"],
            ["Osnabrück"],
            ["Wilhelmshaven"],
            ["Ammerland"],
            ["Aurich"],
            ["Cloppenburg"],
            ["Emsland"],
            ["Friesland"],
            ["Grafschaft Bentheim"],
            ["Leer"],
            ["Oldenburg"],
            ["Osnabrück"],
            ["Vechta"],
            ["Wesermarsch"],
            ["Wittmund"],
            ["Bremen"],
            ["Bremerhaven"],
            ["Düsseldorf"],
            ["Duisburg"],
            ["Essen"],
            ["Krefeld"],
            ["Mönchengladbach"],
            ["Mülheim an der Ruhr"],
            ["Oberhausen"],
            ["Remscheid"],
            ["Solingen"],
            ["Wuppertal"],
            ["Kleve"],
            ["Mettmann"],
            ["Rhein-Kreis Neuss"],
            ["Viersen"],
            ["Wesel"],
            ["Bonn"],
            ["Köln"],
            ["Leverkusen"],
            ["Städteregion Aachen"],
            ["Düren"],
            ["Rhein-Erft-Kreis"],
            ["Euskirchen"],
            ["Heinsberg"],
            ["Oberbergischer Kreis"],
            ["Rheinisch-Bergischer Kreis"],
            ["Rhein-Sieg-Kreis"],
            ["Bottrop"],
            ["Gelsenkirchen"],
            ["Münster"],
            ["Borken"],
            ["Coesfeld"],
            ["Recklinghausen"],
            ["Steinfurt"],
            ["Warendorf"],
            ["Bielefeld"],
            ["Gütersloh"],
            ["Herford"],
            ["Höxter"],
            ["Lippe"],
            ["Minden-Lübbecke"],
            ["Paderborn"],
            ["Bochum"],
            ["Dortmund"],
            ["Hagen"],
            ["Hamm"],
            ["Herne"],
            ["Ennepe-Ruhr-Kreis"],
            ["Hochsauerlandkreis"],
            ["Märkischer Kreis"],
            ["Olpe"],
            ["Siegen-Wittgenstein"],
            ["Soest"],
            ["Unna"],
            ["Darmstadt"],
            ["Frankfurt am Main"],
            ["Offenbach am Main"],
            ["Wiesbaden"],
            ["Bergstraße"],
            ["Darmstadt-Dieburg"],
            ["Groß-Gerau"],
            ["Hochtaunuskreis"],
            ["Main-Kinzig-Kreis"],
            ["Main-Taunus-Kreis"],
            ["Odenwaldkreis"],
            ["Offenbach"],
            ["Rheingau-Taunus-Kreis"],
            ["Wetteraukreis"],
            ["Gießen"],
            ["Lahn-Dill-Kreis"],
            ["Limburg-Weilburg"],
            ["Marburg-Biedenkopf"],
            ["Vogelsbergkreis"],
            ["Kassel"],
            ["Fulda"],
            ["Hersfeld-Rotenburg"],
            ["Kassel"],
            ["Schwalm-Eder-Kreis"],
            ["Waldeck-Frankenberg"],
            ["Werra-Meißner-Kreis"],
            ["Koblenz"],
            ["Ahrweiler"],
            ["Altenkirchen (Westerwald)"],
            ["Bad Kreuznach"],
            ["Birkenfeld"],
            ["Cochem-Zell"],
            ["Mayen-Koblenz"],
            ["Neuwied"],
            ["Rhein-Hunsrück-Kreis"],
            ["Rhein-Lahn-Kreis"],
            ["Westerwaldkreis"],
            ["Trier"],
            ["Bernkastel-Wittlich"],
            ["Eifelkreis Bitburg-Prüm"],
            ["Vulkaneifel"],
            ["Trier-Saarburg"],
            ["Frankenthal (Pfalz)"],
            ["Kaiserslautern"],
            ["Landau in der Pfalz"],
            ["Ludwigshafen am Rhein"],
            ["Mainz"],
            ["Neustadt an der Weinstraße"],
            ["Pirmasens"],
            ["Speyer"],
            ["Worms"],
            ["Zweibrücken"],
            ["Alzey-Worms"],
            ["Bad Dürkheim"],
            ["Donnersbergkreis"],
            ["Germersheim"],
            ["Kaiserslautern"],
            ["Kusel"],
            ["Südliche Weinstraße"],
            ["Rhein-Pfalz-Kreis"],
            ["Mainz-Bingen"],
            ["Südwestpfalz"],
            ["Stuttgart"],
            ["Böblingen"],
            ["Esslingen"],
            ["Göppingen"],
            ["Ludwigsburg"],
            ["Rems-Murr-Kreis"],
            ["Heilbronn"],
            ["Heilbronn"],
            ["Hohenlohekreis"],
            ["Schwäbisch Hall"],
            ["Main-Tauber-Kreis"],
            ["Heidenheim"],
            ["Ostalbkreis"],
            ["Baden-Baden"],
            ["Karlsruhe"],
            ["Karlsruhe"],
            ["Rastatt"],
            ["Heidelberg"],
            ["Mannheim"],
            ["Neckar-Odenwald-Kreis"],
            ["Rhein-Neckar-Kreis"],
            ["Pforzheim"],
            ["Calw"],
            ["Enzkreis"],
            ["Freudenstadt"],
            ["Freiburg im Breisgau"],
            ["Breisgau-Hochschwarzwald"],
            ["Emmendingen"],
            ["Ortenaukreis"],
            ["Rottweil"],
            ["Schwarzwald-Baar-Kreis"],
            ["Tuttlingen"],
            ["Konstanz"],
            ["Lörrach"],
            ["Waldshut"],
            ["Reutlingen"],
            ["Tübingen"],
            ["Zollernalbkreis"],
            ["Ulm"],
            ["Alb-Donau-Kreis"],
            ["Biberach"],
            ["Bodenseekreis"],
            ["Ravensburg"],
            ["Sigmaringen"],
            ["Ingolstadt"],
            ["München"],
            ["Rosenheim"],
            ["Altötting"],
            ["Berchtesgadener Land"],
            ["Bad Tölz-Wolfratshausen"],
            ["Dachau"],
            ["Ebersberg"],
            ["Eichstätt"],
            ["Erding"],
            ["Freising"],
            ["Fürstenfeldbruck"],
            ["Garmisch-Partenkirchen"],
            ["Landsberg am Lech"],
            ["Miesbach"],
            ["Mühldorf a. Inn"],
            ["München"],
            ["Neuburg-Schrobenhausen"],
            ["Pfaffenhofen a.d. Ilm"],
            ["Rosenheim"],
            ["Starnberg"],
            ["Traunstein"],
            ["Weilheim-Schongau"],
            ["Landshut"],
            ["Passau"],
            ["Straubing"],
            ["Deggendorf"],
            ["Freyung-Grafenau"],
            ["Kelheim"],
            ["Landshut"],
            ["Passau"],
            ["Regen"],
            ["Rottal-Inn"],
            ["Straubing-Bogen"],
            ["Dingolfing-Landau"],
            ["Amberg"],
            ["Regensburg"],
            ["Weiden i.d. OPf."],
            ["Amberg-Sulzbach"],
            ["Cham"],
            ["Neumarkt i.d. OPf."],
            ["Neustadt a.d. Waldnaab"],
            ["Regensburg"],
            ["Schwandorf"],
            ["Tirschenreuth"],
            ["Bamberg"],
            ["Bayreuth"],
            ["Coburg"],
            ["Hof"],
            ["Bamberg"],
            ["Bayreuth"],
            ["Coburg"],
            ["Forchheim"],
            ["Hof"],
            ["Kronach"],
            ["Kulmbach"],
            ["Lichtenfels"],
            ["Wunsiedel i. Fichtelgebirge"],
            ["Ansbach"],
            ["Erlangen"],
            ["Fürth"],
            ["Nürnberg"],
            ["Schwabach"],
            ["Ansbach"],
            ["Erlangen-Höchstadt"],
            ["Fürth"],
            ["Nürnberger Land"],
            ["Neustadt a.d. Aisch-Bad Windsheim"],
            ["Roth"],
            ["Weißenburg-Gunzenhausen"],
            ["Aschaffenburg"],
            ["Schweinfurt"],
            ["Würzburg"],
            ["Aschaffenburg"],
            ["Bad Kissingen"],
            ["Rhön-Grabfeld"],
            ["Haßberge"],
            ["Kitzingen"],
            ["Miltenberg"],
            ["Main-Spessart"],
            ["Schweinfurt"],
            ["Würzburg"],
            ["Augsburg"],
            ["Kaufbeuren"],
            ["Kempten (Allgäu)"],
            ["Memmingen"],
            ["Aichach-Friedberg"],
            ["Augsburg"],
            ["Dillingen a.d. Donau"],
            ["Günzburg"],
            ["Neu-Ulm"],
            ["Lindau (Bodensee)"],
            ["Ostallgäu"],
            ["Unterallgäu"],
            ["Donau-Ries"],
            ["Oberallgäu"]
          
    ];






    districtTwo = [
        
            ["Saarland"],
            ["Saarland"],
            ["Saarland"],
            ["Saarland"],
            ["Saarland"],
            ["Saarland"],
            ["Berlin"],
            ["Berlin"],
            ["Berlin"],
            ["Berlin"],
            ["Berlin"],
            ["Berlin"],
            ["Berlin"],
            ["Berlin"],
            ["Berlin"],
            ["Berlin"],
            ["Berlin"],
            ["Berlin"],
            ["Brandenburg"],
            ["Brandenburg"],
            ["Brandenburg"],
            ["Brandenburg"],
            ["Brandenburg"],
            ["Brandenburg"],
            ["Brandenburg"],
            ["Brandenburg"],
            ["Brandenburg"],
            ["Brandenburg"],
            ["Brandenburg"],
            ["Brandenburg"],
            ["Brandenburg"],
            ["Brandenburg"],
            ["Brandenburg"],
            ["Brandenburg"],
            ["Brandenburg"],
            ["Brandenburg"],
            ["Mecklenburg-Vorpommern"],
            ["Mecklenburg-Vorpommern"],
            ["Mecklenburg-Vorpommern"],
            ["Mecklenburg-Vorpommern"],
            ["Mecklenburg-Vorpommern"],
            ["Mecklenburg-Vorpommern"],
            ["Mecklenburg-Vorpommern"],
            ["Mecklenburg-Vorpommern"],
            ["Sachsen"],
            ["Sachsen"],
            ["Sachsen"],
            ["Sachsen"],
            ["Sachsen"],
            ["Sachsen"],
            ["Sachsen"],
            ["Sachsen"],
            ["Sachsen"],
            ["Sachsen"],
            ["Sachsen"],
            ["Sachsen"],
            ["Sachsen"],
            ["Sachsen-Anhalt"],
            ["Sachsen-Anhalt"],
            ["Sachsen-Anhalt"],
            ["Sachsen-Anhalt"],
            ["Sachsen-Anhalt"],
            ["Sachsen-Anhalt"],
            ["Sachsen-Anhalt"],
            ["Sachsen-Anhalt"],
            ["Sachsen-Anhalt"],
            ["Sachsen-Anhalt"],
            ["Sachsen-Anhalt"],
            ["Sachsen-Anhalt"],
            ["Sachsen-Anhalt"],
            ["Sachsen-Anhalt"],
            ["Thüringen"],
            ["Thüringen"],
            ["Thüringen"],
            ["Thüringen"],
            ["Thüringen"],
            ["Thüringen"],
            ["Thüringen"],
            ["Thüringen"],
            ["Thüringen"],
            ["Thüringen"],
            ["Thüringen"],
            ["Thüringen"],
            ["Thüringen"],
            ["Thüringen"],
            ["Thüringen"],
            ["Thüringen"],
            ["Thüringen"],
            ["Thüringen"],
            ["Thüringen"],
            ["Thüringen"],
            ["Thüringen"],
            ["Thüringen"],
            ["Schleswig-Holstein"],
            ["Schleswig-Holstein"],
            ["Schleswig-Holstein"],
            ["Schleswig-Holstein"],
            ["Schleswig-Holstein"],
            ["Schleswig-Holstein"],
            ["Schleswig-Holstein"],
            ["Schleswig-Holstein"],
            ["Schleswig-Holstein"],
            ["Schleswig-Holstein"],
            ["Schleswig-Holstein"],
            ["Schleswig-Holstein"],
            ["Schleswig-Holstein"],
            ["Schleswig-Holstein"],
            ["Schleswig-Holstein"],
            ["Hamburg"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Niedersachsen"],
            ["Bremen"],
            ["Bremen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Nordrhein-Westfalen"],
            ["Hessen"],
            ["Hessen"],
            ["Hessen"],
            ["Hessen"],
            ["Hessen"],
            ["Hessen"],
            ["Hessen"],
            ["Hessen"],
            ["Hessen"],
            ["Hessen"],
            ["Hessen"],
            ["Hessen"],
            ["Hessen"],
            ["Hessen"],
            ["Hessen"],
            ["Hessen"],
            ["Hessen"],
            ["Hessen"],
            ["Hessen"],
            ["Hessen"],
            ["Hessen"],
            ["Hessen"],
            ["Hessen"],
            ["Hessen"],
            ["Hessen"],
            ["Hessen"],
            ["Rheinland-Pfalz"],
            ["Rheinland-Pfalz"],
            ["Rheinland-Pfalz"],
            ["Rheinland-Pfalz"],
            ["Rheinland-Pfalz"],
            ["Rheinland-Pfalz"],
            ["Rheinland-Pfalz"],
            ["Rheinland-Pfalz"],
            ["Rheinland-Pfalz"],
            ["Rheinland-Pfalz"],
            ["Rheinland-Pfalz"],
            ["Rheinland-Pfalz"],
            ["Rheinland-Pfalz"],
            ["Rheinland-Pfalz"],
            ["Rheinland-Pfalz"],
            ["Rheinland-Pfalz"],
            ["Rheinland-Pfalz"],
            ["Rheinland-Pfalz"],
            ["Rheinland-Pfalz"],
            ["Rheinland-Pfalz"],
            ["Rheinland-Pfalz"],
            ["Rheinland-Pfalz"],
            ["Rheinland-Pfalz"],
            ["Rheinland-Pfalz"],
            ["Rheinland-Pfalz"],
            ["Rheinland-Pfalz"],
            ["Rheinland-Pfalz"],
            ["Rheinland-Pfalz"],
            ["Rheinland-Pfalz"],
            ["Rheinland-Pfalz"],
            ["Rheinland-Pfalz"],
            ["Rheinland-Pfalz"],
            ["Rheinland-Pfalz"],
            ["Rheinland-Pfalz"],
            ["Rheinland-Pfalz"],
            ["Rheinland-Pfalz"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Baden-Württemberg"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"],
            ["Bayern"]
          
    ];
*/

var test = [
    ["tet","test"],
    ["tet","test2"],
    ["tet","test3"],
    ["tet","test4"],
];

//console.log(test[2][1]);
/*
var dings;
for (let x = 0; x < 411; x++) {
    
    dings += '["' + districtOne[x] + '", "' + districtTwo[x] + '"],\n';
}

console.log(dings);
*/
}


var district = [
    ["Regionalverband Saarbrücken", "Saarland"],
    ["Merzig-Wadern", "Saarland"],
    ["Neunkirchen", "Saarland"],
    ["Saarlouis", "Saarland"],
    ["Saarpfalz-Kreis", "Saarland"],
    ["St. Wendel", "Saarland"],
    ["Berlin Mitte", "Berlin"],
    ["Berlin Friedrichshain-Kreuzberg", "Berlin"],
    ["Berlin Pankow", "Berlin"],
    ["Berlin Charlottenburg-Wilmersdorf", "Berlin"],
    ["Berlin Spandau", "Berlin"],
    ["Berlin Steglitz-Zehlendorf", "Berlin"],
    ["Berlin Tempelhof-Schöneberg", "Berlin"],
    ["Berlin Neukölln", "Berlin"],
    ["Berlin Treptow-Köpenick", "Berlin"],
    ["Berlin Marzahn-Hellersdorf", "Berlin"],
    ["Berlin Lichtenberg", "Berlin"],
    ["Berlin Reinickendorf", "Berlin"],
    ["Brandenburg an der Havel", "Brandenburg"],
    ["Cottbus", "Brandenburg"],
    ["Frankfurt (Oder)", "Brandenburg"],
    ["Potsdam", "Brandenburg"],
    ["Barnim", "Brandenburg"],
    ["Dahme-Spreewald", "Brandenburg"],
    ["Elbe-Elster", "Brandenburg"],
    ["Havelland", "Brandenburg"],
    ["Märkisch-Oderland", "Brandenburg"],
    ["Oberhavel", "Brandenburg"],
    ["Oberspreewald-Lausitz", "Brandenburg"],
    ["Oder-Spree", "Brandenburg"],
    ["Ostprignitz-Ruppin", "Brandenburg"],
    ["Potsdam-Mittelmark", "Brandenburg"],
    ["Prignitz", "Brandenburg"],
    ["Spree-Neiße", "Brandenburg"],
    ["Teltow-Fläming", "Brandenburg"],
    ["Uckermark", "Brandenburg"],
    ["Rostock", "Mecklenburg-Vorpommern"],
    ["Schwerin", "Mecklenburg-Vorpommern"],
    ["Mecklenburgische Seenplatte", "Mecklenburg-Vorpommern"],
    ["Rostock", "Mecklenburg-Vorpommern"],
    ["Vorpommern-Rügen", "Mecklenburg-Vorpommern"],
    ["Nordwestmecklenburg", "Mecklenburg-Vorpommern"],
    ["Vorpommern-Greifswald", "Mecklenburg-Vorpommern"],
    ["Ludwigslust-Parchim", "Mecklenburg-Vorpommern"],
    ["Chemnitz", "Sachsen"],
    ["Erzgebirgskreis", "Sachsen"],
    ["Mittelsachsen", "Sachsen"],
    ["Vogtlandkreis", "Sachsen"],
    ["Zwickau", "Sachsen"],
    ["Dresden", "Sachsen"],
    ["Bautzen", "Sachsen"],
    ["Görlitz", "Sachsen"],
    ["Meißen", "Sachsen"],
    ["Sächsische Schweiz-Osterzgebirge", "Sachsen"],
    ["Leipzig", "Sachsen"],
    ["Leipzig", "Sachsen"],
    ["Nordsachsen", "Sachsen"],
    ["Dessau-Roßlau", "Sachsen-Anhalt"],
    ["Halle (Saale)", "Sachsen-Anhalt"],
    ["Magdeburg", "Sachsen-Anhalt"],
    ["Altmarkkreis Salzwedel", "Sachsen-Anhalt"],
    ["Anhalt-Bitterfeld", "Sachsen-Anhalt"],
    ["Börde", "Sachsen-Anhalt"],
    ["Burgenlandkreis", "Sachsen-Anhalt"],
    ["Harz", "Sachsen-Anhalt"],
    ["Jerichower Land", "Sachsen-Anhalt"],
    ["Mansfeld-Südharz", "Sachsen-Anhalt"],
    ["Saalekreis", "Sachsen-Anhalt"],
    ["Salzlandkreis", "Sachsen-Anhalt"],
    ["Stendal", "Sachsen-Anhalt"],
    ["Wittenberg", "Sachsen-Anhalt"],
    ["Erfurt", "Thüringen"],
    ["Gera", "Thüringen"],
    ["Jena", "Thüringen"],
    ["Suhl", "Thüringen"],
    ["Weimar", "Thüringen"],
    ["Eichsfeld", "Thüringen"],
    ["Nordhausen", "Thüringen"],
    ["Wartburgkreis", "Thüringen"],
    ["Unstrut-Hainich-Kreis", "Thüringen"],
    ["Kyffhäuserkreis", "Thüringen"],
    ["Schmalkalden-Meiningen", "Thüringen"],
    ["Gotha", "Thüringen"],
    ["Sömmerda", "Thüringen"],
    ["Hildburghausen", "Thüringen"],
    ["Ilm-Kreis", "Thüringen"],
    ["Weimarer Land", "Thüringen"],
    ["Sonneberg", "Thüringen"],
    ["Saalfeld-Rudolstadt", "Thüringen"],
    ["Saale-Holzland-Kreis", "Thüringen"],
    ["Saale-Orla-Kreis", "Thüringen"],
    ["Greiz", "Thüringen"],
    ["Altenburger Land", "Thüringen"],
    ["Flensburg", "Schleswig-Holstein"],
    ["Kiel", "Schleswig-Holstein"],
    ["Lübeck", "Schleswig-Holstein"],
    ["Neumünster", "Schleswig-Holstein"],
    ["Dithmarschen", "Schleswig-Holstein"],
    ["Herzogtum Lauenburg", "Schleswig-Holstein"],
    ["Nordfriesland", "Schleswig-Holstein"],
    ["Ostholstein", "Schleswig-Holstein"],
    ["Pinneberg", "Schleswig-Holstein"],
    ["Plön", "Schleswig-Holstein"],
    ["Rendsburg-Eckernförde", "Schleswig-Holstein"],
    ["Schleswig-Flensburg", "Schleswig-Holstein"],
    ["Segeberg", "Schleswig-Holstein"],
    ["Steinburg", "Schleswig-Holstein"],
    ["Stormarn", "Schleswig-Holstein"],
    ["Hamburg", "Hamburg"],
    ["Braunschweig", "Niedersachsen"],
    ["Salzgitter", "Niedersachsen"],
    ["Wolfsburg", "Niedersachsen"],
    ["Gifhorn", "Niedersachsen"],
    ["Goslar", "Niedersachsen"],
    ["Helmstedt", "Niedersachsen"],
    ["Northeim", "Niedersachsen"],
    ["Peine", "Niedersachsen"],
    ["Wolfenbüttel", "Niedersachsen"],
    ["Göttingen", "Niedersachsen"],
    ["Region Hannover", "Niedersachsen"],
    ["Diepholz", "Niedersachsen"],
    ["Hameln-Pyrmont", "Niedersachsen"],
    ["Hildesheim", "Niedersachsen"],
    ["Holzminden", "Niedersachsen"],
    ["Nienburg (Weser)", "Niedersachsen"],
    ["Schaumburg", "Niedersachsen"],
    ["Celle", "Niedersachsen"],
    ["Cuxhaven", "Niedersachsen"],
    ["Harburg", "Niedersachsen"],
    ["Lüchow-Dannenberg", "Niedersachsen"],
    ["Lüneburg", "Niedersachsen"],
    ["Osterholz", "Niedersachsen"],
    ["Rotenburg (Wümme)", "Niedersachsen"],
    ["Heidekreis", "Niedersachsen"],
    ["Stade", "Niedersachsen"],
    ["Uelzen", "Niedersachsen"],
    ["Verden", "Niedersachsen"],
    ["Delmenhorst", "Niedersachsen"],
    ["Emden", "Niedersachsen"],
    ["Oldenburg (Oldb)", "Niedersachsen"],
    ["Osnabrück", "Niedersachsen"],
    ["Wilhelmshaven", "Niedersachsen"],
    ["Ammerland", "Niedersachsen"],
    ["Aurich", "Niedersachsen"],
    ["Cloppenburg", "Niedersachsen"],
    ["Emsland", "Niedersachsen"],
    ["Friesland", "Niedersachsen"],
    ["Grafschaft Bentheim", "Niedersachsen"],
    ["Leer", "Niedersachsen"],
    ["Oldenburg", "Niedersachsen"],
    ["Osnabrück", "Niedersachsen"],
    ["Vechta", "Niedersachsen"],
    ["Wesermarsch", "Niedersachsen"],
    ["Wittmund", "Niedersachsen"],
    ["Bremen", "Bremen"],
    ["Bremerhaven", "Bremen"],
    ["Düsseldorf", "Nordrhein-Westfalen"],
    ["Duisburg", "Nordrhein-Westfalen"],
    ["Essen", "Nordrhein-Westfalen"],
    ["Krefeld", "Nordrhein-Westfalen"],
    ["Mönchengladbach", "Nordrhein-Westfalen"],
    ["Mülheim an der Ruhr", "Nordrhein-Westfalen"],
    ["Oberhausen", "Nordrhein-Westfalen"],
    ["Remscheid", "Nordrhein-Westfalen"],
    ["Solingen", "Nordrhein-Westfalen"],
    ["Wuppertal", "Nordrhein-Westfalen"],
    ["Kleve", "Nordrhein-Westfalen"],
    ["Mettmann", "Nordrhein-Westfalen"],
    ["Rhein-Kreis Neuss", "Nordrhein-Westfalen"],
    ["Viersen", "Nordrhein-Westfalen"],
    ["Wesel", "Nordrhein-Westfalen"],
    ["Bonn", "Nordrhein-Westfalen"],
    ["Köln", "Nordrhein-Westfalen"],
    ["Leverkusen", "Nordrhein-Westfalen"],
    ["Städteregion Aachen", "Nordrhein-Westfalen"],
    ["Düren", "Nordrhein-Westfalen"],
    ["Rhein-Erft-Kreis", "Nordrhein-Westfalen"],
    ["Euskirchen", "Nordrhein-Westfalen"],
    ["Heinsberg", "Nordrhein-Westfalen"],
    ["Oberbergischer Kreis", "Nordrhein-Westfalen"],
    ["Rheinisch-Bergischer Kreis", "Nordrhein-Westfalen"],
    ["Rhein-Sieg-Kreis", "Nordrhein-Westfalen"],
    ["Bottrop", "Nordrhein-Westfalen"],
    ["Gelsenkirchen", "Nordrhein-Westfalen"],
    ["Münster", "Nordrhein-Westfalen"],
    ["Borken", "Nordrhein-Westfalen"],
    ["Coesfeld", "Nordrhein-Westfalen"],
    ["Recklinghausen", "Nordrhein-Westfalen"],
    ["Steinfurt", "Nordrhein-Westfalen"],
    ["Warendorf", "Nordrhein-Westfalen"],
    ["Bielefeld", "Nordrhein-Westfalen"],
    ["Gütersloh", "Nordrhein-Westfalen"],
    ["Herford", "Nordrhein-Westfalen"],
    ["Höxter", "Nordrhein-Westfalen"],
    ["Lippe", "Nordrhein-Westfalen"],
    ["Minden-Lübbecke", "Nordrhein-Westfalen"],
    ["Paderborn", "Nordrhein-Westfalen"],
    ["Bochum", "Nordrhein-Westfalen"],
    ["Dortmund", "Nordrhein-Westfalen"],
    ["Hagen", "Nordrhein-Westfalen"],
    ["Hamm", "Nordrhein-Westfalen"],
    ["Herne", "Nordrhein-Westfalen"],
    ["Ennepe-Ruhr-Kreis", "Nordrhein-Westfalen"],
    ["Hochsauerlandkreis", "Nordrhein-Westfalen"],
    ["Märkischer Kreis", "Nordrhein-Westfalen"],
    ["Olpe", "Nordrhein-Westfalen"],
    ["Siegen-Wittgenstein", "Nordrhein-Westfalen"],
    ["Soest", "Nordrhein-Westfalen"],
    ["Unna", "Nordrhein-Westfalen"],
    ["Darmstadt", "Hessen"],
    ["Frankfurt am Main", "Hessen"],
    ["Offenbach am Main", "Hessen"],
    ["Wiesbaden", "Hessen"],
    ["Bergstraße", "Hessen"],
    ["Darmstadt-Dieburg", "Hessen"],
    ["Groß-Gerau", "Hessen"],
    ["Hochtaunuskreis", "Hessen"],
    ["Main-Kinzig-Kreis", "Hessen"],
    ["Main-Taunus-Kreis", "Hessen"],
    ["Odenwaldkreis", "Hessen"],
    ["Offenbach", "Hessen"],
    ["Rheingau-Taunus-Kreis", "Hessen"],
    ["Wetteraukreis", "Hessen"],
    ["Gießen", "Hessen"],
    ["Lahn-Dill-Kreis", "Hessen"],
    ["Limburg-Weilburg", "Hessen"],
    ["Marburg-Biedenkopf", "Hessen"],
    ["Vogelsbergkreis", "Hessen"],
    ["Kassel", "Hessen"],
    ["Fulda", "Hessen"],
    ["Hersfeld-Rotenburg", "Hessen"],
    ["Kassel", "Hessen"],
    ["Schwalm-Eder-Kreis", "Hessen"],
    ["Waldeck-Frankenberg", "Hessen"],
    ["Werra-Meißner-Kreis", "Hessen"],
    ["Koblenz", "Rheinland-Pfalz"],
    ["Ahrweiler", "Rheinland-Pfalz"],
    ["Altenkirchen (Westerwald)", "Rheinland-Pfalz"],
    ["Bad Kreuznach", "Rheinland-Pfalz"],
    ["Birkenfeld", "Rheinland-Pfalz"],
    ["Cochem-Zell", "Rheinland-Pfalz"],
    ["Mayen-Koblenz", "Rheinland-Pfalz"],
    ["Neuwied", "Rheinland-Pfalz"],
    ["Rhein-Hunsrück-Kreis", "Rheinland-Pfalz"],
    ["Rhein-Lahn-Kreis", "Rheinland-Pfalz"],
    ["Westerwaldkreis", "Rheinland-Pfalz"],
    ["Trier", "Rheinland-Pfalz"],
    ["Bernkastel-Wittlich", "Rheinland-Pfalz"],
    ["Eifelkreis Bitburg-Prüm", "Rheinland-Pfalz"],
    ["Vulkaneifel", "Rheinland-Pfalz"],
    ["Trier-Saarburg", "Rheinland-Pfalz"],
    ["Frankenthal (Pfalz)", "Rheinland-Pfalz"],
    ["Kaiserslautern", "Rheinland-Pfalz"],
    ["Landau in der Pfalz", "Rheinland-Pfalz"],
    ["Ludwigshafen am Rhein", "Rheinland-Pfalz"],
    ["Mainz", "Rheinland-Pfalz"],
    ["Neustadt an der Weinstraße", "Rheinland-Pfalz"],
    ["Pirmasens", "Rheinland-Pfalz"],
    ["Speyer", "Rheinland-Pfalz"],
    ["Worms", "Rheinland-Pfalz"],
    ["Zweibrücken", "Rheinland-Pfalz"],
    ["Alzey-Worms", "Rheinland-Pfalz"],
    ["Bad Dürkheim", "Rheinland-Pfalz"],
    ["Donnersbergkreis", "Rheinland-Pfalz"],
    ["Germersheim", "Rheinland-Pfalz"],
    ["Kaiserslautern", "Rheinland-Pfalz"],
    ["Kusel", "Rheinland-Pfalz"],
    ["Südliche Weinstraße", "Rheinland-Pfalz"],
    ["Rhein-Pfalz-Kreis", "Rheinland-Pfalz"],
    ["Mainz-Bingen", "Rheinland-Pfalz"],
    ["Südwestpfalz", "Rheinland-Pfalz"],
    ["Stuttgart", "Baden-Württemberg"],
    ["Böblingen", "Baden-Württemberg"],
    ["Esslingen", "Baden-Württemberg"],
    ["Göppingen", "Baden-Württemberg"],
    ["Ludwigsburg", "Baden-Württemberg"],
    ["Rems-Murr-Kreis", "Baden-Württemberg"],
    ["Heilbronn", "Baden-Württemberg"],
    ["Heilbronn", "Baden-Württemberg"],
    ["Hohenlohekreis", "Baden-Württemberg"],
    ["Schwäbisch Hall", "Baden-Württemberg"],
    ["Main-Tauber-Kreis", "Baden-Württemberg"],
    ["Heidenheim", "Baden-Württemberg"],
    ["Ostalbkreis", "Baden-Württemberg"],
    ["Baden-Baden", "Baden-Württemberg"],
    ["Karlsruhe", "Baden-Württemberg"],
    ["Karlsruhe", "Baden-Württemberg"],
    ["Rastatt", "Baden-Württemberg"],
    ["Heidelberg", "Baden-Württemberg"],
    ["Mannheim", "Baden-Württemberg"],
    ["Neckar-Odenwald-Kreis", "Baden-Württemberg"],
    ["Rhein-Neckar-Kreis", "Baden-Württemberg"],
    ["Pforzheim", "Baden-Württemberg"],
    ["Calw", "Baden-Württemberg"],
    ["Enzkreis", "Baden-Württemberg"],
    ["Freudenstadt", "Baden-Württemberg"],
    ["Freiburg im Breisgau", "Baden-Württemberg"],
    ["Breisgau-Hochschwarzwald", "Baden-Württemberg"],
    ["Emmendingen", "Baden-Württemberg"],
    ["Ortenaukreis", "Baden-Württemberg"],
    ["Rottweil", "Baden-Württemberg"],
    ["Schwarzwald-Baar-Kreis", "Baden-Württemberg"],
    ["Tuttlingen", "Baden-Württemberg"],
    ["Konstanz", "Baden-Württemberg"],
    ["Lörrach", "Baden-Württemberg"],
    ["Waldshut", "Baden-Württemberg"],
    ["Reutlingen", "Baden-Württemberg"],
    ["Tübingen", "Baden-Württemberg"],
    ["Zollernalbkreis", "Baden-Württemberg"],
    ["Ulm", "Baden-Württemberg"],
    ["Alb-Donau-Kreis", "Baden-Württemberg"],
    ["Biberach", "Baden-Württemberg"],
    ["Bodenseekreis", "Baden-Württemberg"],
    ["Ravensburg", "Baden-Württemberg"],
    ["Sigmaringen", "Baden-Württemberg"],
    ["Ingolstadt", "Bayern"],
    ["München", "Bayern"],
    ["Rosenheim", "Bayern"],
    ["Altötting", "Bayern"],
    ["Berchtesgadener Land", "Bayern"],
    ["Bad Tölz-Wolfratshausen", "Bayern"],
    ["Dachau", "Bayern"],
    ["Ebersberg", "Bayern"],
    ["Eichstätt", "Bayern"],
    ["Erding", "Bayern"],
    ["Freising", "Bayern"],
    ["Fürstenfeldbruck", "Bayern"],
    ["Garmisch-Partenkirchen", "Bayern"],
    ["Landsberg am Lech", "Bayern"],
    ["Miesbach", "Bayern"],
    ["Mühldorf a. Inn", "Bayern"],
    ["München", "Bayern"],
    ["Neuburg-Schrobenhausen", "Bayern"],
    ["Pfaffenhofen a.d. Ilm", "Bayern"],
    ["Rosenheim", "Bayern"],
    ["Starnberg", "Bayern"],
    ["Traunstein", "Bayern"],
    ["Weilheim-Schongau", "Bayern"],
    ["Landshut", "Bayern"],
    ["Passau", "Bayern"],
    ["Straubing", "Bayern"],
    ["Deggendorf", "Bayern"],
    ["Freyung-Grafenau", "Bayern"],
    ["Kelheim", "Bayern"],
    ["Landshut", "Bayern"],
    ["Passau", "Bayern"],
    ["Regen", "Bayern"],
    ["Rottal-Inn", "Bayern"],
    ["Straubing-Bogen", "Bayern"],
    ["Dingolfing-Landau", "Bayern"],
    ["Amberg", "Bayern"],
    ["Regensburg", "Bayern"],
    ["Weiden i.d. OPf.", "Bayern"],
    ["Amberg-Sulzbach", "Bayern"],
    ["Cham", "Bayern"],
    ["Neumarkt i.d. OPf.", "Bayern"],
    ["Neustadt a.d. Waldnaab", "Bayern"],
    ["Regensburg", "Bayern"],
    ["Schwandorf", "Bayern"],
    ["Tirschenreuth", "Bayern"],
    ["Bamberg", "Bayern"],
    ["Bayreuth", "Bayern"],
    ["Coburg", "Bayern"],
    ["Hof", "Bayern"],
    ["Bamberg", "Bayern"],
    ["Bayreuth", "Bayern"],
    ["Coburg", "Bayern"],
    ["Forchheim", "Bayern"],
    ["Hof", "Bayern"],
    ["Kronach", "Bayern"],
    ["Kulmbach", "Bayern"],
    ["Lichtenfels", "Bayern"],
    ["Wunsiedel i. Fichtelgebirge", "Bayern"],
    ["Ansbach", "Bayern"],
    ["Erlangen", "Bayern"],
    ["Fürth", "Bayern"],
    ["Nürnberg", "Bayern"],
    ["Schwabach", "Bayern"],
    ["Ansbach", "Bayern"],
    ["Erlangen-Höchstadt", "Bayern"],
    ["Fürth", "Bayern"],
    ["Nürnberger Land", "Bayern"],
    ["Neustadt a.d. Aisch-Bad Windsheim", "Bayern"],
    ["Roth", "Bayern"],
    ["Weißenburg-Gunzenhausen", "Bayern"],
    ["Aschaffenburg", "Bayern"],
    ["Schweinfurt", "Bayern"],
    ["Würzburg", "Bayern"],
    ["Aschaffenburg", "Bayern"],
    ["Bad Kissingen", "Bayern"],
    ["Rhön-Grabfeld", "Bayern"],
    ["Haßberge", "Bayern"],
    ["Kitzingen", "Bayern"],
    ["Miltenberg", "Bayern"],
    ["Main-Spessart", "Bayern"],
    ["Schweinfurt", "Bayern"],
    ["Würzburg", "Bayern"],
    ["Augsburg", "Bayern"],
    ["Kaufbeuren", "Bayern"],
    ["Kempten (Allgäu)", "Bayern"],
    ["Memmingen", "Bayern"],
    ["Aichach-Friedberg", "Bayern"],
    ["Augsburg", "Bayern"],
    ["Dillingen a.d. Donau", "Bayern"],
    ["Günzburg", "Bayern"],
    ["Neu-Ulm", "Bayern"],
    ["Lindau (Bodensee)", "Bayern"],
    ["Ostallgäu", "Bayern"],
    ["Unterallgäu", "Bayern"],
    ["Donau-Ries", "Bayern"],
    ["Oberallgäu", "Bayern"]
];


console.log(district[120][0]);
